"""Configuration for FAL speech-to-text models."""

from .constants import (
    MODEL_ENDPOINTS,
    MODEL_DISPLAY_NAMES,
    MODEL_PRICING,
    MODEL_DEFAULTS,
    INPUT_REQUIREMENTS,
    SUPPORTED_LANGUAGES,
    MODEL_CATEGORIES,
    MODEL_RECOMMENDATIONS,
    PROCESSING_TIME_ESTIMATES,
)

__all__ = [
    "MODEL_ENDPOINTS",
    "MODEL_DISPLAY_NAMES",
    "MODEL_PRICING",
    "MODEL_DEFAULTS",
    "INPUT_REQUIREMENTS",
    "SUPPORTED_LANGUAGES",
    "MODEL_CATEGORIES",
    "MODEL_RECOMMENDATIONS",
    "PROCESSING_TIME_ESTIMATES",
]
